export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


export const ADD_PROFILE = "ADD_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_FAILED = "PROFILE_FAILED";

export const ADD_STORIES = "ADD_STORIES";
export const STORIES_LOADING = "STORIES_LOADING";
export const STORIES_FAILED = "STORIES_FAILED"

export const ADD_DESTINATION = "ADD_DESTINATION";
export const DESTINATION_LOADING = "DESTINATION_LOADING";
export const DESTINATION_FAILED = "DESTINATION_FAILED";

export const ADD_REGISTRATION = "ADD_REGISTRATION";
export const REGISTRATION_LOADING = "REGISTRATION_LOADING";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const ADD_SERVICES = "ADD_SERVICES";
export const SERVICES_LOADING = "SERVICES_LOADING";
export const SERVICES_FAILED = "SERVICES_FAILED";

export const ADD_REQUEST = "ADD_REQUEST";
export const REQUEST_LOADING = "REQUEST_LOADING";
export const REQUEST_FAILED = "REQUEST_FAILED";


export const ADD_FACILITY = "ADD_FACILITY";
export const FACILITY_LOADING = "FACILITY_LOADING";
export const FACILITY_FAILED = "FACILITY_FAILED";


export const ADD_UPROFILE = "ADD_UPROFILE";
export const UPROFILE_LOADING = "UPROFILE_LOADING";
export const UPROFILE_FAILED = "UPROFILE_FAILED";


export const ADD_TRIP = "ADD_TRIP";
export const TRIP_LOADING = "TRIP_LOADING";
export const TRIP_FAILED = "TRIP_FAILED";

export const ADD_USER = "ADD_USER";
export const USER_LOADING = "USER_LOADING";
export const USER_FAILED = "USER_FAILED";

export const ADD_STORY = "ADD_STORY";
export const STORY_LOADING = "STORY_LOADING";
export const STORY_FAILED = "STORY_FAILED"