export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


export const ADD_PROFILE = "ADD_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_FAILED = "PROFILE_FAILED";

export const ADD_REGISTRATION = "ADD_REGISTRATION";
export const REGISTRATION_LOADING = "REGISTRATION_LOADING";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";